### ISSUE TITLE
Fullscreen is disabled and can't be added via custom Parameter

### ISSUE THREAD

**Issue by LimeGrove** [jprusik/custom-yt-embed#2]
I can't allow fullscreen no matter which settings I choose in the Embed Generator.

Example:
`<iframe src="https://www.youtube-nocookie.com/embed/LXb3EKWsInQ?modestbranding=1&showinfo=0&rel=0&theme=light&color=white" width="800" height="450" frameborder="0"></iframe>`

When adding **allowfullscreen=""** in the end manually it does work:
`<iframe src="https://www.youtube-nocookie.com/embed/LXb3EKWsInQ?modestbranding=1&showinfo=0&rel=0&theme=light&color=white" width="800" height="450" frameborder="0" **allowfullscreen=""**></iframe>`

Is there a way to achieve this in the Embed Generator?

**Comment by jprusik** [comment]
This should be resolved now, as of d9cb9e771901d0b011043634d47562eaf7bf34e7
