### ISSUE TITLE
Suggesting an additional option to (more easily) accommodate the 'title="" parameter in the YouTube iFrame for 508 Compliance

### ISSUE THREAD

**Issue by Jimbobwe** [jprusik/custom-yt-embed#3]
Jonathan:

Great tool, man! But could I get ya to make one more tweak?

As you know, web accessibility is a huge issue, particularly now. In terms of video accessibility, in order to achieve 508 Compliance, all video links must contain a descriptive title regarding that video for users of assistive technology (i.e.: screen readers). At very least, the screen readers must be able to read the video link's title from the website or mobile app's page source, to then be audibly translated to the visually impaired user. 

Since YouTube uses iFrames with which to embed their streaming videos, it means that YT embed codes should include at least a placeholder for the iFrame 'title=' parameter. However, up until fairly recently, Google did not feature a title tag within their iFrames. Finally now there is one included in the YT embed codes, albeit the all-encompassing and generic value, "YouTube video player", which is completely divorced from any title information which the author may have provided at the time the video was first uploaded or later edited. 

So while this does circumvent an accessibility hole for which Google had been guilty for much too long, it also creates more busywork for the developer, who still must manually add the title, but now for the additional purpose of replacing the placeholder, which by default cannot be altered in any other way — and IMO should have always been tied to the video's original title provided at upload time.

That said, your very cool **YT Custom Video Embed Generator** unfortunately follows along the same path of utility as YouTube had done previously, with no addressing of the title requirement within the iFrame embed code. So I now humbly request a slight upgrade to accommodate this provision of a custom value for the title="" attribute. 

I realize that it's currently possible to do this currently with your tool, but it requires a bit of syntax bastardization in the "Custom Parameters" field, via the juggling of spaces and quotation marks. Specifically, here's what I had to do to make it work:

— The only way (that I could figure) to construct a video title (custom or otherwise) tag using the "Custom Parameters" field was like this:
`" title="My Custom Video Title`

— ...which produces a final iFrame embed code that includes the desired video `title=` attribute:
`<iframe src="https://www.youtube.com/embed/QH2-TGUlwu4?" title="My Custom Video Title" width="560" height="315" frameborder="0"></iframe>`

So if you could make all this a little more seamless it'd be awesome! 

Thanks again for all your hard work!

Jim

**Comment by jprusik** [comment]
I totally get it and agree. When I originally built the tool, this wasn't a thing and I've since relied on user reports/feedback for any important updates, since I don't actively maintain it.

I think this should be quick and easy, so I'll try to carve out some time to do this over the weekend 👍 

(alternatively, you should feel free to submit a PR as well, if you feel like getting your hands dirty 😉 )

**Comment by jprusik** [comment]
I've updated the tool to automatically use the fetched video ID if the metadata is available. Otherwise, it will use the value of `A YouTube video`. The user may, at any time, supply an alternative title using the new video title input.

This should address the issue raised in the ticket; thanks for the report 👍

**Comment by Jimbobwe** [comment]
Thank you, Sir!
